kumuluzee:
  datasources:
    - jndi-name: jdbc/TutorialDS
      connection-url: jdbc:postgresql://ec2-54-228-174-49.eu-west-1.compute.amazonaws.com:5432/d9fksifgpu2qos
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
      pool:
        max-size: 5
  persistence-units:
    - name: "tutorial-jpa"