kumuluzee:
  datasources:
    - jndi-name: jdbc/TutorialDS
      connection-url: ${DB_CONNECTION_URL}
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
      pool:
        max-size: 5
  persistence-units:
    - name: "tutorial-jpa"